### ISSUE TITLE
Add command-line option for host example 

### ISSUE THREAD

**Issue by piedoom** [rust-dsp/rust-vst#22]
Instead of a hard-coded string, use a command line option.  This refers to this [discussion](https://github.com/rust-dsp/rust-vst/pull/21#discussion-diff-150735142L21).

**Comment by Walther** [comment]
I tried looking at this and bumped into something interesting.

AFAIU, this should work: `cargo run --example simple_host`, as the example is a) under subdirectory `examples/` and b) explicitly defined under an `[[example]]` declaration in `Cargo.toml`. This should make Cargo find the named example and run it (and give us the helpful suggestion "usage: simple_host path/to/vst", and hint the end user towards running the command with a path to a VST as a parameter).

However, what actually happens is this:

```
cargo run --example simple_host
error: example target `simple_host` is a library and cannot be executed
```

The behavior for detecting things as libraries or binaries has been implemented in [this PR](https://github.com/rust-lang/cargo/pull/5485).

---

Another curiosity: if you _remove_ this part from `Cargo.toml`:

```
[[example]]
name = "simple_host"
crate-type = ["bin"]
```

and run `cargo run --example simple_host`, you get:

```
warning: An explicit [[example]] section is specified in Cargo.toml which currently
disables Cargo from automatically inferring other example targets.
This inference behavior will change in the Rust 2018 edition and the following
files will be included as a example target:

* /Users/walther/git/rust-vst/examples/simple_host.rs

This is likely to break cargo build or cargo test as these files may not be
ready to be compiled as a example target today. You can future-proof yourself
and disable this warning by adding `autoexamples = false` to your [package]
section. You may also move the files to a location where Cargo would not
automatically infer them to be a target, such as in subfolders.

For more information on this warning you can consult
https://github.com/rust-lang/cargo/issues/5330
error: no example target named `simple_host`
```

Additionally, if you remove _all of the example declarations_ from the `Cargo.toml`, `cargo run --example simple_host` starts working! However, then the library-vs-binary distinction/detection apparently turns completely off, because now you can run `cargo run --example sine_synth` and get ``error[E0601]: `main` function not found in crate `sine_synth`` from the compiler, not triggering the "is a library" -error.

---

Could this be a bug in the library / binary detection algorithm in Cargo? Maybe `crate-type = ["bin"]
` is not detected correctly if some of the examples are declared as `crate-type = ["cdylib"]`? Or maybe the entire project is labelled as a binary because the project itself has no `main.rs`, only `lib.rs`, even if some of the examples would have a `fn main()` and be declared as a `bin`?

**Comment by zyvitski** [comment]
This seems like something that would be worth bringing up in one of the rust forums. It seems like either therr Is something non obvious we need to do to make it work or a big. So it would be best to get in touch with someone who knows

**Comment by Walther** [comment]
Moved the `cargo run --example` problem into its own issue, as per suggestion on the Telegram chat. This issue could be solved separately from that one.

**Comment by Walther** [comment]
AFAIU, this should work now with `cargo run --example simple_host /absolute/path/vstfile`

<img width="843" alt="screen shot 2019-03-03 at 20 49 21" src="https://user-images.githubusercontent.com/2943750/53711208-e0d75100-3df5-11e9-95ae-660b5d4180ff.png">
